### ISSUE TITLE
zsh_rc_dir is undefined

### ISSUE THREAD

**Issue by kostyrev** [hnakamur/direnv-ansible_role#1]
Hi @hnakamur!
there's no `defaults/main.yml` with default vars.
How you use this role?

**Comment by hnakamur** [comment]
Hi @akostyrev,
Thanks for a catch.
It seems I forgot to add default vars files.
Ah, I find `zsh_rc_dir` is defined at https://github.com/hnakamur/ansible-role-zsh/blob/d76af8ca1a0b38fd99899a916829cf11cac8ab15/defaults/main.yml#L15

I'm afraid I forgot how I used this library.
Perhaps I copied this role to
https://github.com/hnakamur/macbook_setup
and used this playbook.
However actually I do not use this playbook anymore.

**Comment by kostyrev** [comment]
ok, np
